server:
  host: 0.0.0.0
  port: 8080

redis:
  host: redis # Use redis as hostname if you use redis from docker
  port: 6379
  password: ""
  fixed-window-db: 0
  token-bucket-db: 1

rate-limiter:
  fixed-window:
    max-requests: 5
    time-frame-ms: 60000
  token-bucket:
    max-tokens: 2
    refill-rate: 1 # token/s