version: "3.9"
services:
  redis:
    image: redis:7-alpine
    container_name: my-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: my-go-app
    depends_on:
      - redis
    ports:
      - "8080:8080"
    volumes:
      - ./config.yml:/root/config.yml
